version: '3.0'

services:
  db:
    image: postgres:9.6.5-alpine
    ports:
      - "5432:5432"
    hostname: db
    environment:
      POSTGRES_PASSWORD: test

  wait_dbs:
    image: "waisbrot/wait"
    restart: "no"
    environment:
      TARGETS: "db:5432"
      TIMEOUT: 60
    depends_on:
      - db

  create_dbs:
    image: "hbpmip/create-databases:1.0.0"
    restart: "no"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_ADMIN_USER: postgres
      DB_ADMIN_PASSWORD: test
      DB4: portal
      USER4: portal
      PASSWORD4: portalpwd
    depends_on:
      - db

  portalbackend:
    image: hbpmip/portal-backend:5.0.1
    restart: "no"
    ports:
      - "8080:8080"
      - "8089:8089"
    environment:
      PORTAL_DB_URL: jdbc:postgresql://db:5432/portal
      PORTAL_DB_SERVER: db:5432
      PORTAL_DB_USER: portal
      PORTAL_DB_PASSWORD: portalpwd
      CONTEXT_PATH: /services
      AUTHENTICATION: 0
      CLIENT_ID: 3ee62745-4080-4928-b5e7-acd15c042552
      CLIENT_SECRET: SaNJbC2YFHPhPM_nGMyQo4jyAh3x1LI4si0hBCpOYLZO2IQ448ob5AzSoG8r8uW9QwU3T5JimL-tGiJ1b7tmAA
      FRONTEND_LOGIN_URL: ${FRONTEND_URL}/services/login/hbp
      FRONTEND_AFTER_LOGIN_URL: ${FRONTEND_URL}/
      FRONTEND_AFTER_LOGOUT_URL: ${FRONTEND_URL}/services/login/hbp
      EXAREME_URL: http://88.197.39.116:9090
      WORKFLOW_URL: http://88.197.53.36/Middleware_API-1.0.0-SNAPSHOT/api
      JWT_SECRET: "secret"
      LOGGING_LEVEL_WEB: INFO
      LOGGING_LEVEL_HIBERNATE: INFO
      SESSION_TIMEOUT: 2592000
      RELEASE_STAGE: "testing"
      DATACENTER_LOCATION: "$HOST"
      CONTAINER_ORCHESTRATION: "docker-compose"
    depends_on:
      - db
    volumes:
      - ./data:/opt/portal/api

  wait_portal_backend:
    image: "waisbrot/wait"
    restart: "no"
    environment:
      TARGETS: "portalbackend:8080"
      TIMEOUT: 60
    depends_on:
      - portalbackend

  frontend:
    image: hbpmip/portal-frontend:5.1.1
    depends_on:
      - portalbackend
    ports:
      - "80:80"
    environment:
      WORKER_PROCESSES: 1
      ERROR_LOG_LEVEL: warn
      PORTAL_VIRTUAL_HOST: frontend
      PORTAL_BACKEND_SERVER: portalbackend:8080
      PORTAL_BACKEND_CONTEXT: services
      MODE: federation
      INSTANCE_NAME: "MIP 5.0.0"
      VERSION: "5.0.0"
      TRACKER_ID: UA-80660232-5
      GALAXY_API_URL: "http://localhost:8090/api"
      GALAXY_APACHE_URL: "http://88.197.53.100/nativeGalaxy"
